config/routes.rb
MyCodeBlog::Application.routes.draw do
  
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:create, :destroy]
  
  root to: 'static_pages#home'
  match '/contact', to: 'static_pages#contact'
  match '/resume', to: 'static_pages#resume'
  
  match '/signup', to: 'users#new'
  match '/signin',  to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete
  

end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :content, :user_id 
  belongs_to :user
  
  default_scope order: 'posts.created_at DESC'
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :name, :password, :password_confirmation, :posts
  has_many :posts
  has_secure_password
  
  before_save :create_remember_token
  
  private 
  def create_remember_token
    self.remember_token = SecureRandom.urlsafe_base64
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_filter :signed_in_user

  def create
    @post = current_user.posts.build(params[:post])
    if @post.save
      flash[:success] = "Micropost created!"
      redirect_to current_user
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by_email(params[:session][:email])
      if user && user.authenticate(params[:session][:password])
        sign_in user
        redirect_to root_path
      end
  end
  
  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
  
  def resume
    @render_number = 0
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end
  def create
    @user = User.new(params[:user])
    if(params[:user][:email] == "MikeHasAMac@gmail.com")
      if(@user.save)
        sign_in @user
        redirect_to @user
      end
    else
      redirect_to root_path
    end
  end
    
    
    def show
      if signed_in?
        @user = current_user
        @posts = @user.posts.paginate(page: params[:page])
        @post = @user.posts.build
      else
        @users = User.all
        @user = @users[0]
        @posts = @user.posts.paginate(page: params[:page])
      end
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
      cookies.permanent[:remember_token] = user.remember_token
      self.current_user = user
  end
    
  def signed_in?
      !current_user.nil?
  end  
    
  def current_user=(user)
      @current_user = user
  end
  
  def current_user
      @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end
  
  def signed_in_user
      unless signed_in?
        store_location
        redirect_to signin_url, notice: "Please sign in."
      end
    end
  
  def sign_out
      self.current_user = nil
      cookies.delete(:remember_token)
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="navbar">
    <div class="container">
	  <nav>
		<hr>
		  <ul class="nav pull-right"> 
		    <li><%= link_to "Contact", contact_path %></li>
		    <li><%= link_to "Resume", resume_path %></li>
		  </ul>
	  </nav>
    </div>
</div>

app/views/layouts/_header.html.erb
<% @users = User.all %>
<div id="header" class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
	  <%= link_to "Mike's Blog", @users[0], id: "logo" %>
	  <nav>
	    <ul class="nav pull-right">  
	      <li><%= link_to "Home", root_path %></li>
		  <li><%= link_to "View My Blog", @users[0] %></li>
		<% if signed_in? %>
		  <li><%= link_to "Sign out", signout_path, method: "delete"%>
		<% else %>
		  <li><%= link_to "Sign in", signin_path %>
		  <% if @users.count < 1 %>
		  <li><%= link_to "Sign up", signup_path %></li>
		  <% end %>
		<% end %>
        </ul>	
	  </nav>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyCodeBlog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>

<%= yield %>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/posts/_post.html.erb
<li>
  <span class="content"><%= post.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(post.created_at) %> ago.
  </span>
</li>

app/views/shared/_post.html.erb
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/_post_form.html.erb
<h3>New Post</h3>
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/shared/post_form.html.erb
<%= form_for @post do |f| %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new post..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-large btn-primary" %>
<% end %>

app/views/static_pages/contact.html.erb
<h1 class="yellow">Michael Peterson</h1>
<h3 class="blue">Phone:</h3>
<ul>
	<li>Work: (757)686-6950 ext: 6440</li>
	<li>Cell: (757)559-4712</li>
</ul>
<h3 class="blue">Email:</h3>
<ul>
	<li>Work: Michael.Peterson@truestonefed.com</li>
	<li>Personal: MikeHasAMac@gmail.com</li>
</ul> 

app/views/static_pages/home.html.erb
<h1>This is my Blog!</h1>
<div class="center">
<p>
  My name is Michael Peterson.
 I have been a .Net applications developer for a few years now (working mainly with Winform and WPF applications). 
 As an applications developer, diving into the world of web design/development has been a bit overwhelming to say the least. 
 This blog is my way of capturing this journey and putting it into words.  
This is mainly for my own benefit, as it's always beneficial to put your thoughts down in words, although I invite you to follow along.	
</p>
</div>

app/views/static_pages/resume.html.erb
<h1 class="yellow">Michael Peterson</h1>
<h3 class="blue">Summary of Qualifications</h3>
<div class="centered">Strong object-oriented programmer with both a top level education and professional experience.  A strong ability to learn and adapt quickly as well as experience with leading-edge programming tools.  Experience developing and testing fully functional software applications using test driven devlopment.</div> </br> 
Experience Includes:
<ul>
	<li>Extensive C# / .NET development</li>
	<li>Sql Server Experience</li>
	<li>Java Development</li>
	<li>Ruby on Rails / HTML5 / CSS experience</li>
	<li>C/C++ Experience</li> 
</ul>
<h3 class="blue">Education</h3>
<div class="centered">Bachelor of Science in Computer Science, May 2012, Old Dominion University, Norfolk, Virginia</div>
<h3 class="blue">Work Experience</h3>
<ul>
	<li><b>Programmer Analyst, Truestone, Suffolk, VA 2012-present</b></br>
		<div class="centered">Worked as a software engineer on the Coast Guard Data Distribution System (CGDDS).  Created Test plans to verify the corrections made to counteract System Trouble Reports.  Did the majority of the design work for the newest revision, 1.0.5.0, including a complete rewrite of the client application adding large amounts of new features.  Built a Unit Testing Framework into the newest revision using the Model-View-Presenter architecture and NUnit.  The system was developed using the .NET framework, the Windows Forms library, and the C# programming language.  The system includes both a core service and a client (GUI) application.</div></li>
	<li><b>Software Engineering Intern, WR Systems, Norfolk, VA 2011-2012</b>
		<div class="centered">Developed a software application for testing and monitoring conventional navigation equipment.  This application was developed using the .NET framework, the Windows Presentation Foundation (WPF), and the C# programming language.  Features included the ability to log and graphically represent data in real time.  Also developed a WPF browser application with the same capabilities.  </div></li>

app/views/users/new.html.erb
<div class="row">
	<div class="span6 offset3">

      <%= form_for @user do |f| %>
	    <%= f.label :name %>
	    <%= f.text_field :name %>
	
	    <%= f.label :email %>
	    <%= f.text_field :email %>
	
	    <%= f.label :password %>
	    <%= f.password_field :password %>
	
	    <%= f.label :password_confirmation %>
	    <%= f.password_field :password_confirmation %>

	    <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
      <% end %>
    </div>
</div>

app/views/users/show.html.erb
<div class="row">
  <aside class="span3">
	<section>
      <% if signed_in? %>
	    <%= render 'shared/post_form' %>
      <% end %>
    </section>
  </aside>
<% if signed_in? %>
  <div class="span7 rightsided">
<% else %>
  <div class="span7">
	<% end %>
      <% if @user.posts.any? %>
        <h3>Posts (<%= @user.posts.count %>)</h3>
        <ol class="posts">
          <%= render @posts %>
        </ol>
        <%= will_paginate @posts %>
      <% end %>
    </div>
  </div>
</div>